name:                exp-hs-pango
version:             0.1.0.0
github:              "mitsuji/exp-hs-pango"
license:             BSD3
author:              "Takamasa Mitsuji"
maintainer:          "tkms@mitsuji.org"
copyright:           "2018 Takamasa Mitsuji"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mitsuji/exp-hs-pango#readme>

dependencies:
- base >= 4.7 && < 5
- pango
- cairo
- gtk

library:
  source-dirs: src

executables:
  exp-hs-pango-exe:
    main:                Layout.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exp-hs-pango

tests:
  exp-hs-pango-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exp-hs-pango
